### ISSUE TITLE
Chonky allows an empty folderChain but doesn't allow going up the parent folder to a en empty chain

### ISSUE THREAD

**Issue by jffaust** [TimboKZ/Chonky#97] opened 2021-07-02 16:35 UTC
Starting from an empty `folderChain: [] ` : 
![image](https://user-images.githubusercontent.com/4367222/124304023-24ab0400-db31-11eb-9fd6-08f4216e0073.png)

I can navigate to a child folder, but then I cannot go back:
![image](https://user-images.githubusercontent.com/4367222/124304083-3b515b00-db31-11eb-96fc-9e95229569d4.png)

If I go another level deeper, the button to go up becomes enabled:
![image](https://user-images.githubusercontent.com/4367222/124304706-14dfef80-db32-11eb-8881-8c68a97ab5b2.png)

This behavior doesn't seem coherent. Is this by design?

If I want to work around this at the database layer, I'd have to add a root directory to all the paths.

I could also work around this on the frontend side by having some kind of virtual virtual root folder but it adds to the complexity when interacting with the paths provided by the database.

**Comment by TimboKZ** [comment] 2022-01-08 19:29
Hi, this is indeed by design. The assumption is that the user will always define a name for the root folder.

**Comment by TimboKZ** [comment] 2022-01-08 21:38
Closing the issue as this is intended behaviour (that works quite well), feel free to reopen if you have more questions.

**Closed as completed by TimboKZ** 2022-01-08 21:38 UTC
Labels: help wanted
